export const animeGenres = [
  { value: "1", label: "Action" },
  { value: "2", label: "Adventure" },
  { value: "4", label: "Comedy" },
  { value: "6", label: "Demons" },
  { value: "8", label: "Drama" },
  { value: "9", label: "Ecchi" },
  { value: "10", label: "Fantasy" },
  { value: "11", label: "Game" },
  { value: "12", label: "Hentai" },
  { value: "13", label: "Historical" },
  { value: "14", label: "Horror" },
  { value: "15", label: "Kids" },
  { value: "16", label: "Magic" },
  { value: "17", label: "Martial Arts" },
  { value: "18", label: "Mecha" },
  { value: "19", label: "Music" },
  { value: "20", label: "Parody" },
  { value: "21", label: "Samurai" },
  { value: "22", label: "Romance" },
  { value: "23", label: "School" },
  { value: "24", label: "Sci-Fi" },
  { value: "25", label: "Shoujo" },
  { value: "26", label: "Girls Love" },
  { value: "27", label: "Shounen" },
  { value: "28", label: "Boys Love" },
  { value: "29", label: "Space" },
  { value: "30", label: "Sports" },
  { value: "31", label: "Super Power" },
  { value: "34", label: "Slice of Life" },
  { value: "35", label: "Supernatural" },
  { value: "36", label: "Military" },
  { value: "37", label: "Police" },
  { value: "38", label: "Psychological" },
  { value: "40", label: "Seinen" },
  { value: "41", label: "Josei" },
  { value: "39", label: "Thriller" },
];

export const mangaGenres = [
  { value: "1", label: "Action" },
  { value: "2", label: "Adventure" },
  { value: "3", label: "Cars" },
  { value: "4", label: "Comedy" },
  { value: "5", label: "Dementia" },
  { value: "6", label: "Demons" },
  { value: "8", label: "Drama" },
  { value: "9", label: "Ecchi" },
  { value: "10", label: "Fantasy" },
  { value: "11", label: "Game" },
  { value: "35", label: "Harem" },
  { value: "12", label: "Hentai" },
  { value: "13", label: "Historical" },
  { value: "14", label: "Horror" },
  { value: "15", label: "Kids" },
  { value: "16", label: "Magic" },
  { value: "17", label: "Martial Arts" },
  { value: "18", label: "Mecha" },
  { value: "19", label: "Music" },
  { value: "7", label: "Mystery" },
  { value: "20", label: "Parody" },
  { value: "22", label: "Romance" },
  { value: "21", label: "Samurai" },
  { value: "23", label: "School" },
  { value: "24", label: "Sci-Fi" },
  { value: "25", label: "Shoujo" },
  { value: "26", label: "Shoujo Ai" },
  { value: "27", label: "Shounen" },
  { value: "28", label: "Shounen Ai" },
  { value: "29", label: "Space" },
  { value: "30", label: "Sports" },
  { value: "31", label: "Super Power" },
  { value: "32", label: "Vampire" },
  { value: "33", label: "Yaoi" },
  { value: "34", label: "Yuri" },
];
