export const animeGenres = [
  { value: "action", label: "Action" },
  { value: "adventure", label: "Adventure" },
  { value: "comedy", label: "Comedy" },
  { value: "demon", label: "Demon" },
  { value: "drama", label: "Drama" },
  { value: "ecchi", label: "Ecchi" },
  { value: "fantasy", label: "Fantasy" },
  { value: "game", label: "Game" },
  { value: "hentai", label: "Hentai" },
  { value: "historical", label: "Historical" },
  { value: "horror", label: "Horror" },
  { value: "idol", label: "Idols" },
  { value: "isekai", label: "Isekai" },
  { value: "josei", label: "Josei" },
  { value: "love-triangle", label: "Love Triangle" },
  { value: "magic", label: "Magic" },
  { value: "magic-girls", label: "Magical Girls" },
  { value: "mecha", label: "Mecha" },
  { value: "military", label: "Military" },
  { value: "music", label: "Music" },
  { value: "parody", label: "Parody" },
  { value: "pets", label: "Pets" },
  { value: "police", label: "Police" },
  { value: "psychological", label: "Psychological" },
  { value: "romance", label: "Romance" },
  { value: "sci-fi", label: "Sci-Fi" },
  { value: "samurai", label: "Samurai" },
  { value: "school", label: "School" },
  { value: "seinen", label: "Seinen" },
  { value: "shoujo", label: "Shoujo" },
  { value: "shounen", label: "Shounen" },
  { value: "slice-of-life", label: "Slice of Life" },
  { value: "sports", label: "Sports" },
  { value: "super-power", label: "Super Power" },
  { value: "supernatural", label: "Supernatural" },
  { value: "vampire", label: "Vampire" },
  { value: "workplace", label: "Workplace" },
];
